extends Node

class_name Constants

const VERTICAL_ACCELERATION = 0.1
const VERTICAL_DECELERATION = 0.2
const MAX_VERTICAL_SPEED = 5.0

const HORIZONTAL_ACCELERATION = 0.1
const HORIZONTAL_DECELERATION = 0.2
const MAX_HORIZONTAL_SPEED = 5.0

const BOB_POSITION_FACTORS = [2.3, 70.0]
const BOB_ROTATION_FACTORS = [1.42, 40.0]

const MAX_ENEMY_SPEED = 1.0
